server:
  port: ${APPLICATION_HTTP_PORT:8080}
  max-http-header-size: 64KB

spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  freemarker:
    charset: utf-8


---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: sa
    url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE;
  freemarker:
    cache: false
  jpa:
    database: h2
  h2:
    console:
      enabled: true

graphql:
  packages:
    - "kr.inplat.graphql"
